import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    nav_home: 'Home',
    nav_classification: 'Classification',
    nav_about: 'About',
    nav_dashboard: 'Dashboard',
    hero_title: 'Explainable AI',
    hero_subtitle: 'Fatigue Detection',
    hero_desc: 'Advanced classification system to detect human emotional fatigue levels through audio analysis using Deep Learning based on CNN architecture with explainable AI transparency.',
    btn_start_analysis: 'Start Analysis',
    btn_learn_more: 'Learn More',
    features_title: 'Key Features',
    feature_ai_title: 'AI-Powered Analysis',
    feature_ai_desc: 'Utilizes YAMNet transfer learning combined with custom acoustic features for precise fatigue detection.',
    feature_realtime_title: 'Real-time Processing',
    feature_realtime_desc: 'Get instant results with our optimized deep learning pipeline running on Hugging Face Spaces.',
    feature_xai_title: 'XAI Visualization',
    feature_xai_desc: 'Understand model decisions through spectrograms and feature importance visualizations.',
    stats_title: 'Statistic Overview',
    stat_total: 'Total Analyzed',
    stat_avg_conf: 'Avg Confidence',
    stat_low: 'Low Fatigue',
    stat_high: 'High Fatigue',
    confidence_trend: 'Confidence Trend',
    class_distribution: 'Class Distribution',
    pred_count: 'Prediction Count by Class',
    system_flow: 'System Architecture Flow',
    flow_subtitle: 'End-to-end pipeline from dataset to deployment',
    cta_title: 'Ready to Analyze?',
    cta_desc: 'Upload your audio or record your voice to get instant fatigue classification results.',
    cta_button: 'Get Started',
    predict_title: 'Explainable AI',
    predict_subtitle: 'Emotional Fatigue Classification',
    audio_input_title: 'Audio Input',
    audio_input_desc: 'Upload or record audio for fatigue analysis',
    tab_upload: 'Upload File',
    tab_record: 'Record Voice',
    drop_title: 'Drag & Drop Audio File',
    drop_subtitle: 'or click to select file from device',
    btn_analyze: 'Analyze Fatigue',
    btn_analyzing: 'Analyzing...',
    results_title: 'Analysis Results',
    results_subtitle: 'Explainable AI fatigue classification',
    fatigue_level: 'Fatigue Level',
    classification_result: 'Classification Result',
    prob_distribution: 'Probability Distribution',
    per_class_conf: 'Per Class Confidence',
    spectrogram_title: 'Audio Spectrogram',
    spectrogram_subtitle: 'Frequency-Time Visualization',
    feature_importance: 'Feature Importance',
    lime_title: 'LIME Explanation',
    lime_subtitle: 'Local Interpretable Model-agnostic Explanations',
    shap_title: 'SHAP Explanation',
    shap_subtitle: 'Feature contributions to prediction',
    health_title: 'Health Recommendations',
    health_subtitle: 'Personalized advice based on your fatigue level',
    api_response: 'API Response (JSON)',
    btn_export_json: 'Export JSON',
    history_title: 'History',
    history_subtitle: 'Previous analysis results',
    history_empty: 'No analysis history yet. Upload or record audio to get started.',
    btn_clear: 'Clear',
    col_time: 'Time',
    col_file: 'File',
    col_prediction: 'Prediction',
    col_confidence: 'Confidence',
    about_title: 'About the System',
    about_subtitle: 'Explainable AI for Emotional Fatigue Classification',
    system_info: 'System Information',
    system_info_desc: 'Technical details about the classification system',
    model_arch: 'Model Architecture',
    audio_features: 'Audio Features',
    meet_devs: 'Meet the Developers',
    devs_subtitle: 'The team behind Explainable AI',
    source_code: 'Source Code',
    source_desc: 'Explore the full source code of this project on GitHub.',
    view_github: 'View on GitHub',
    loading_title: 'Analyzing Audio',
    loading_subtitle: 'Processing audio features with Explainable AI',
    stage_connecting: 'Connecting to server',
    stage_upload: 'Uploading audio file',
    stage_processing: 'Processing audio features',
    stage_predicting: 'Running CNN prediction',
    stage_finalizing: 'Generating visualization',
    error_no_file: 'No file selected. Please upload or record audio first.',
    error_api_config: 'API not configured. Please go to Configure page first.',
    error_analysis_failed: 'Analysis failed.',
    health_low_title: 'You are in good condition!',
    health_low_desc: 'Your fatigue level is low. Keep maintaining your healthy habits.',
    health_low_tips: [
      'Maintain 7-9 hours of quality sleep',
      'Continue regular exercise routine',
      'Stay hydrated throughout the day',
      'Take short breaks during work',
    ],
    health_medium_title: 'Moderate fatigue detected',
    health_medium_desc: 'Your body shows signs of moderate fatigue. Consider taking rest.',
    health_medium_tips: [
      'Prioritize sleep and aim for 8+ hours',
      'Reduce caffeine intake after 2 PM',
      'Practice meditation or deep breathing',
      'Consider a short nap (20-30 minutes)',
      'Light stretching or yoga recommended',
    ],
    health_high_title: 'High fatigue warning!',
    health_high_desc: 'Your fatigue level is high. Immediate rest and recovery needed.',
    health_high_tips: [
      'Get immediate rest and sleep',
      'Avoid driving or operating machinery',
      'Consult a healthcare professional',
      'Take a break from screen time',
      'Practice relaxation techniques',
      'Consider taking a day off',
    ],
    pdf_title: 'Fatigue Analysis Report',
    pdf_generated: 'Generated on',
    pdf_patient: 'Analysis ID',
    pdf_model: 'Model',
    pdf_confidence: 'Confidence Score',
    pdf_class: 'Classification',
    pdf_recommendations: 'Recommendations',
    pdf_features: 'Feature Analysis',
    pdf_disclaimer: 'This report is generated by an AI system and should not replace professional medical advice.',
    btn_download_pdf: 'Download PDF Report',
    footer_desc: 'Emotional Fatigue Classification System',
    footer_rights: 'All rights reserved.',
    // ===== ABOUT PAGE KEYS =====
    about_system_name: 'Explainable AI Emotional Fatigue Detection System',
    about_system_desc: 'is a Deep Learning-based classification system developed to analyze human emotional fatigue levels through audio signals. The system uses a CNN architecture with Transfer Learning (YAMNet) capable of classifying into 3 fatigue categories.',
    about_model_desc: 'The model is trained using audio features such as MFCC, Mel Spectrogram, Spectral Centroid, RMS Energy, and Zero Crossing Rate. With the XAI approach, the system provides transparency in decision-making through important feature visualizations.',
    about_backend: 'Backend',
    about_framework: 'Framework',
    about_model: 'Model',
    about_frontend: 'Frontend',
    low: 'LOW',
    medium: 'MEDIUM',
    high: 'HIGH',
    confidence: 'Confidence',
    fatigue: 'Fatigue',
    time: 'Time',
    frequency: 'Frequency',
    intensity: 'Intensity',
    linear: 'Linear',
    mel_scale: 'Mel Scale',
    recording_tips: 'Recording Tips',
    tip_speak_clearly: 'Speak clearly and at a normal pace',
    tip_minimize_noise: 'Minimize background noise',
    tip_distance: 'Keep microphone 10-15 cm from your mouth',
    tip_max_duration: 'Maximum recording duration',
    tip_format: 'Audio saved as 16kHz WAV (PCM)',
    theme_dark: 'Dark Mode',
    theme_light: 'Light Mode',
    feature_rms: 'RMS Energy',
    feature_pitch: 'Pitch (F0)',
    feature_centroid: 'Spectral Centroid',
    feature_zcr: 'Zero Crossing Rate',
    feature_silence: 'Silence Ratio',
    feature_mfcc: 'MFCC Coefficients',
    feature_mel: 'Mel Spectrogram',
    feature_tempo: 'Tempo',
    feature_jitter: 'Jitter',
    contributes_to: 'contributes to',
    prediction: 'prediction',
    lime_explanation: 'LIME highlights which audio features most influenced the model\'s decision for this specific sample. Green bars support the predicted class, red bars oppose it.',
    shap_explanation: 'SHAP values show how each feature pushes the prediction away from the base value. Longer bars indicate stronger influence on the final decision.',
    // ===== HOMEPAGE & DASHBOARD NEW KEYS =====
    badge_cnn: 'CNN-based Emotional Fatigue Classification System',
    stat_overview: 'Statistic Overview',
    stat_realtime: 'Real-time statistic and prediction summary',
    sys_flow: 'System Architecture Flow',
    sys_flow_sub: 'End-to-end pipeline from dataset to deployment',
    cta_ready: 'Ready to Analyze?',
    cta_ready_desc: 'Upload your audio or record your voice to get instant fatigue classification results.',
    cta_button_start: 'Get Started',
    flow_dataset: 'Dataset Engineering',
    flow_dataset_sub: 'Data Collection & Preprocessing',
    flow_dl: 'Deep Learning Model',
    flow_dl_sub: 'CNN + Transfer Learning',
    flow_backend: 'Backend System',
    flow_backend_sub: 'API & Model Serving',
    flow_frontend: 'Frontend System',
    flow_frontend_sub: 'React Dashboard',
    flow_deploy: 'Deployment',
    flow_deploy_sub: 'Cloud Production',
    flow_detail_collect: 'Collect Audio Dataset from Responden',
    flow_detail_understand: 'Data Understanding & EDA',
    flow_detail_preprocess: 'Data Preprocessing',
    flow_detail_extract: 'Feature Extraction (MFCC, Spectrogram)',
    flow_detail_yamnet: 'YAMNet Feature Extraction',
    flow_detail_arch: 'CNN Architecture Design',
    flow_detail_train: 'Model Training & Validation',
    flow_detail_hyper: 'Hyperparameter Tuning',
    flow_detail_flask: 'Flask REST API Development',
    flow_detail_integrate: 'Model Integration & Inference',
    flow_detail_pipeline: 'Audio Processing Pipeline',
    flow_detail_error: 'Error Handling & Logging',
    flow_detail_dashboard: 'Interactive Dashboard Design',
    flow_detail_upload: 'Audio Upload & Recording',
    flow_detail_viz: 'Real-time Visualization',
    flow_detail_ui: 'Responsive UI/UX',
    flow_detail_hf: 'Hugging Face Spaces Deployment',
    flow_detail_cicd: 'CI/CD Pipeline',
    flow_detail_monitor: 'Performance Monitoring',
    flow_detail_scale: 'Scalability Testing',
    dashboard_title: 'Dashboard',
    dashboard_desc: 'Real-time monitoring and analytics for fatigue classification system',
    hist_analytics: 'History Analytics',
    pred_trends: 'Prediction trends and class distribution',
    ready_classify: 'Ready to Classify?',
    ready_classify_desc: 'Upload audio or record your voice for instant fatigue analysis.',
    start_classify: 'Start Classification',
  },
  id: {
    nav_home: 'Beranda',
    nav_classification: 'Klasifikasi',
    nav_about: 'Tentang',
    nav_dashboard: 'Dashboard',
    hero_title: 'Explainable AI',
    hero_subtitle: 'Deteksi Kelelahan',
    hero_desc: 'Sistem klasifikasi canggih untuk mendeteksi tingkat kelelahan emosional manusia melalui analisis audio menggunakan Deep Learning berbasis arsitektur CNN dengan transparansi AI yang dapat dijelaskan.',
    btn_start_analysis: 'Mulai Analisis',
    btn_learn_more: 'Pelajari Lebih',
    features_title: 'Fitur Utama',
    feature_ai_title: 'Analisis Berbasis AI',
    feature_ai_desc: 'Menggunakan transfer learning YAMNet yang dikombinasikan dengan fitur akustik kustom untuk deteksi kelelahan yang presisi.',
    feature_realtime_title: 'Pemrosesan Real-time',
    feature_realtime_desc: 'Dapatkan hasil instan dengan pipeline deep learning yang dioptimalkan berjalan di Hugging Face Spaces.',
    feature_xai_title: 'Visualisasi XAI',
    feature_xai_desc: 'Pahami keputusan model melalui spektrogram dan visualisasi pentingnya fitur.',
    stats_title: 'Ikhtisar Statistik',
    stat_total: 'Total Dianalisis',
    stat_avg_conf: 'Rata-rata Kepercayaan',
    stat_low: 'Kelelahan Rendah',
    stat_high: 'Kelelahan Tinggi',
    confidence_trend: 'Tren Kepercayaan',
    class_distribution: 'Distribusi Kelas',
    pred_count: 'Jumlah Prediksi per Kelas',
    system_flow: 'Alur Arsitektur Sistem',
    flow_subtitle: 'Pipeline end-to-end dari dataset hingga deployment',
    cta_title: 'Siap Menganalisis?',
    cta_desc: 'Unggah audio Anda atau rekam suara Anda untuk mendapatkan hasil klasifikasi kelelahan secara instan.',
    cta_button: 'Mulai',
    predict_title: 'Explainable AI',
    predict_subtitle: 'Klasifikasi Kelelahan Emosional',
    audio_input_title: 'Input Audio',
    audio_input_desc: 'Unggah atau rekam audio untuk analisis kelelahan',
    tab_upload: 'Unggah File',
    tab_record: 'Rekam Suara',
    drop_title: 'Seret & Lepas File Audio',
    drop_subtitle: 'atau klik untuk memilih file dari perangkat',
    btn_analyze: 'Analisis Kelelahan',
    btn_analyzing: 'Menganalisis...',
    results_title: 'Hasil Analisis',
    results_subtitle: 'Klasifikasi kelelahan Explainable AI',
    fatigue_level: 'Tingkat Kelelahan',
    classification_result: 'Hasil Klasifikasi',
    prob_distribution: 'Distribusi Probabilitas',
    per_class_conf: 'Kepercayaan per Kelas',
    spectrogram_title: 'Spektrogram Audio',
    spectrogram_subtitle: 'Visualisasi Frekuensi-Waktu',
    feature_importance: 'Pentingnya Fitur',
    lime_title: 'Penjelasan LIME',
    lime_subtitle: 'Penjelasan Model Lokal yang Dapat Diinterpretasikan',
    shap_title: 'Penjelasan SHAP',
    shap_subtitle: 'Kontribusi fitur terhadap prediksi',
    health_title: 'Rekomendasi Kesehatan',
    health_subtitle: 'Saran personal berdasarkan tingkat kelelahan Anda',
    api_response: 'Respons API (JSON)',
    btn_export_json: 'Ekspor JSON',
    history_title: 'Riwayat',
    history_subtitle: 'Hasil analisis sebelumnya',
    history_empty: 'Belum ada riwayat analisis. Unggah atau rekam audio untuk memulai.',
    btn_clear: 'Hapus',
    col_time: 'Waktu',
    col_file: 'File',
    col_prediction: 'Prediksi',
    col_confidence: 'Kepercayaan',
    about_title: 'Tentang Sistem',
    about_subtitle: 'Explainable AI untuk Klasifikasi Kelelahan Emosional',
    system_info: 'Informasi Sistem',
    system_info_desc: 'Detail teknis tentang sistem klasifikasi',
    model_arch: 'Arsitektur Model',
    audio_features: 'Fitur Audio',
    meet_devs: 'Tim Pengembang',
    devs_subtitle: 'Tim di balik Explainable AI',
    source_code: 'Kode Sumber',
    source_desc: 'Jelajahi kode sumber lengkap proyek ini di GitHub.',
    view_github: 'Lihat di GitHub',
    loading_title: 'Menganalisis Audio',
    loading_subtitle: 'Memproses fitur audio dengan Explainable AI',
    stage_connecting: 'Menghubungkan ke server',
    stage_upload: 'Mengunggah file audio',
    stage_processing: 'Memproses fitur audio',
    stage_predicting: 'Menjalankan prediksi CNN',
    stage_finalizing: 'Menghasilkan visualisasi',
    error_no_file: 'Tidak ada file yang dipilih. Silakan unggah atau rekam audio terlebih dahulu.',
    error_api_config: 'API belum dikonfigurasi. Silakan ke halaman Konfigurasi terlebih dahulu.',
    error_analysis_failed: 'Analisis gagal.',
    health_low_title: 'Anda dalam kondisi baik!',
    health_low_desc: 'Tingkat kelelahan Anda rendah. Pertahankan kebiasaan sehat Anda.',
    health_low_tips: [
      'Pertahankan tidur berkualitas 7-9 jam',
      'Lanjutkan rutinitas olahraga teratur',
      'Tetap terhidrasi sepanjang hari',
      'Ambil istirahat singkat saat bekerja',
    ],
    health_medium_title: 'Kelelahan sedang terdeteksi',
    health_medium_desc: 'Tubuh Anda menunjukkan tanda kelelahan sedang. Pertimbangkan untuk beristirahat.',
    health_medium_tips: [
      'Utamakan tidur dan targetkan 8+ jam',
      'Kurangi asupan kafein setelah jam 2 sore',
      'Praktikkan meditasi atau pernapasan dalam',
      'Pertimbangkan tidur siang singkat (20-30 menit)',
      'Peregangan ringan atau yoga direkomendasikan',
    ],
    health_high_title: 'Peringatan kelelahan tinggi!',
    health_high_desc: 'Tingkat kelelahan Anda tinggi. Istirahat dan pemulihan segera diperlukan.',
    health_high_tips: [
      'Segera istirahat dan tidur',
      'Hindari mengemudi atau mengoperasikan mesin',
      'Konsultasikan dengan profesional kesehatan',
      'Istirahat dari waktu layar',
      'Praktikkan teknik relaksasi',
      'Pertimbangkan mengambil cuti',
    ],
    pdf_title: 'Laporan Analisis Kelelahan',
    pdf_generated: 'Dibuat pada',
    pdf_patient: 'ID Analisis',
    pdf_model: 'Model',
    pdf_confidence: 'Skor Kepercayaan',
    pdf_class: 'Klasifikasi',
    pdf_recommendations: 'Rekomendasi',
    pdf_features: 'Analisis Fitur',
    pdf_disclaimer: 'Laporan ini dihasilkan oleh sistem AI dan tidak boleh menggantikan saran medis profesional.',
    btn_download_pdf: 'Unduh Laporan PDF',
    footer_desc: 'Sistem Klasifikasi Kelelahan Emosional',
    footer_rights: 'Hak cipta dilindungi.',
    // ===== ABOUT PAGE KEYS =====
    about_system_name: 'Sistem Deteksi Kelelahan Emosional Explainable AI',
    about_system_desc: 'adalah sistem klasifikasi berbasis Deep Learning yang dikembangkan untuk menganalisis tingkat kelelahan emosional manusia melalui sinyal audio. Sistem menggunakan arsitektur CNN dengan Transfer Learning (YAMNet) yang mampu mengklasifikasikan ke dalam 3 kategori kelelahan.',
    about_model_desc: 'Model dilatih menggunakan fitur audio seperti MFCC, Mel Spektrogram, Sentroid Spektral, Energi RMS, dan Zero Crossing Rate. Dengan pendekatan XAI, sistem memberikan transparansi dalam pengambilan keputusan melalui visualisasi fitur penting.',
    about_backend: 'Backend',
    about_framework: 'Framework',
    about_model: 'Model',
    about_frontend: 'Frontend',
    low: 'RENDAH',
    medium: 'SEDANG',
    high: 'TINGGI',
    confidence: 'Kepercayaan',
    fatigue: 'Kelelahan',
    time: 'Waktu',
    frequency: 'Frekuensi',
    intensity: 'Intensitas',
    linear: 'Linear',
    mel_scale: 'Skala Mel',
    recording_tips: 'Tips Rekaman',
    tip_speak_clearly: 'Bicara dengan jelas dan kecepatan normal',
    tip_minimize_noise: 'Minimalkan kebisingan latar belakang',
    tip_distance: 'Jaga mikrofon 10-15 cm dari mulut Anda',
    tip_max_duration: 'Durasi rekaman maksimum',
    tip_format: 'Audio disimpan sebagai 16kHz WAV (PCM)',
    theme_dark: 'Mode Gelap',
    theme_light: 'Mode Terang',
    feature_rms: 'Energi RMS',
    feature_pitch: 'Pitch (F0)',
    feature_centroid: 'Sentroid Spektral',
    feature_zcr: 'Zero Crossing Rate',
    feature_silence: 'Rasio Diam',
    feature_mfcc: 'Koefisien MFCC',
    feature_mel: 'Mel Spektrogram',
    feature_tempo: 'Tempo',
    feature_jitter: 'Jitter',
    contributes_to: 'berkontribusi pada',
    prediction: 'prediksi',
    lime_explanation: 'LIME menyoroti fitur audio mana yang paling memengaruhi keputusan model untuk sampel spesifik ini. Batang hijau mendukung kelas yang diprediksi, batang merah menentangnya.',
    shap_explanation: 'Nilai SHAP menunjukkan bagaimana setiap fitur mendorong prediksi menjauh dari nilai dasar. Batang yang lebih panjang menunjukkan pengaruh yang lebih kuat pada keputusan akhir.',
    // ===== HOMEPAGE & DASHBOARD NEW KEYS =====
    badge_cnn: 'Sistem Klasifikasi Kelelahan Emosional Berbasis CNN',
    stat_overview: 'Ikhtisar Statistik',
    stat_realtime: 'Ringkasan statistik dan prediksi real-time',
    sys_flow: 'Alur Arsitektur Sistem',
    sys_flow_sub: 'Pipeline end-to-end dari dataset hingga deployment',
    cta_ready: 'Siap Menganalisis?',
    cta_ready_desc: 'Unggah audio Anda atau rekam suara Anda untuk mendapatkan hasil klasifikasi kelelahan secara instan.',
    cta_button_start: 'Mulai',
    flow_dataset: 'Dataset Engineering',
    flow_dataset_sub: 'Pengumpulan & Pra-pemrosesan Data',
    flow_dl: 'Model Deep Learning',
    flow_dl_sub: 'CNN + Transfer Learning',
    flow_backend: 'Sistem Backend',
    flow_backend_sub: 'API & Model Serving',
    flow_frontend: 'Sistem Frontend',
    flow_frontend_sub: 'Dashboard React',
    flow_deploy: 'Deployment',
    flow_deploy_sub: 'Cloud Production',
    flow_detail_collect: 'Kumpulkan Dataset Audio dari Responden',
    flow_detail_understand: 'Pemahaman Data & EDA',
    flow_detail_preprocess: 'Pra-pemrosesan Data',
    flow_detail_extract: 'Ekstraksi Fitur (MFCC, Spektrogram)',
    flow_detail_yamnet: 'Ekstraksi Fitur YAMNet',
    flow_detail_arch: 'Desain Arsitektur CNN',
    flow_detail_train: 'Pelatihan & Validasi Model',
    flow_detail_hyper: 'Penyetelan Hyperparameter',
    flow_detail_flask: 'Pengembangan Flask REST API',
    flow_detail_integrate: 'Integrasi & Inferensi Model',
    flow_detail_pipeline: 'Pipeline Pemrosesan Audio',
    flow_detail_error: 'Penanganan Error & Logging',
    flow_detail_dashboard: 'Desain Dashboard Interaktif',
    flow_detail_upload: 'Unggah & Rekam Audio',
    flow_detail_viz: 'Visualisasi Real-time',
    flow_detail_ui: 'UI/UX Responsif',
    flow_detail_hf: 'Deployment Hugging Face Spaces',
    flow_detail_cicd: 'Pipeline CI/CD',
    flow_detail_monitor: 'Pemantauan Performa',
    flow_detail_scale: 'Pengujian Skalabilitas',
    dashboard_title: 'Dashboard',
    dashboard_desc: 'Pemantauan dan analitik real-time untuk sistem klasifikasi kelelahan',
    hist_analytics: 'Analitik Riwayat',
    pred_trends: 'Tren prediksi dan distribusi kelas',
    ready_classify: 'Siap Klasifikasi?',
    ready_classify_desc: 'Unggah audio atau rekam suara Anda untuk analisis kelelahan instan.',
    start_classify: 'Mulai Klasifikasi',
  }
};

const AppContext = createContext();

export const AppProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'en';
  });

  const [theme, setTheme] = useState(() => {
    return localStorage.getItem('app_theme') || 'dark';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('app_theme', theme);
    if (theme === 'light') {
      document.documentElement.classList.add('light-mode');
      document.documentElement.classList.remove('dark-mode');
    } else {
      document.documentElement.classList.add('dark-mode');
      document.documentElement.classList.remove('light-mode');
    }
  }, [theme]);

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'id' : 'en');
  };

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  return (
    <AppContext.Provider value={{ language, theme, t, toggleLanguage, toggleTheme }}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) throw new Error('useApp must be used within AppProvider');
  return context;
};